### ISSUE TITLE
Prefix with I should also prefix field types with I

### ISSUE THREAD

**Issue by Evertras** [Evertras/typescript-cs-poco#11]
````C#
MyPoco
{
  public MyOtherPoco Field { get; set; }
}
````

should turn into

````typescript
interface IMyPoco {
  Field: IMyOtherPoco;
}
````

**Comment by San7hos** [comment]
This is now the last issue that is stopping me from using this over TypeLite

**Comment by Evertras** [comment]
Sorry for the delay on this, life has been busy!  Got this fixed now though I believe, let me know if you run into any specific issues.
