### ISSUE TITLE
Option - generate into one file

### ISSUE THREAD

**Issue by San7hos** [Evertras/typescript-cs-poco#12]
Add option to generate the interfaces into one file, possibly also specifying a namespace.

**Comment by Evertras** [comment]
Concatenating everything into one file is best done with the wrapper at https://github.com/Evertras/gulp-typescript-cs-poco .  Right now Gulp is the only wrapper supported, but that has an easy concat() to use.  This particular package is only built to handle one file at a time, so you'll have to manually concat things if you're not using Gulp.  I'll also be updating the Readme to point there for clarity's sake.

I'll definitely be adding a base namespace option though.  Look for that shortly.

**Comment by Evertras** [comment]
1.3.0 now contains a baseNamespace option to wrap everything into a base module name.

**Comment by San7hos** [comment]
Sorry, I have placed the issue in a wrong repository. Anyway, I do not see the option to create only single file in the gulp wrapper (I use gulp). That could be solved with gulp-concat. However, a problem arises when you want to concat the files in one and then wrap them with a module/namespace. There might be a solution with some other gulp extension which I am not aware of.

**Comment by Evertras** [comment]
Do concat() first, then send it to the poco generator.  It will wrap all of them into baseNamespace cleanly.  Doing concat() second will still work, but you'll just have many individual module declarations... this is still valid, just ugly.

**Comment by Evertras** [comment]
Just found a bug while testing this.  I need to make it export the interfaces.  Once that's fixed this will work as described, though!

**Comment by San7hos** [comment]
I see, I didn't expect doing concat first would work. Thanks! Great job btw.

**Comment by Evertras** [comment]
Really glad it's helpful!  I also looked at TypeLite, and my issue was that with the new tech stack we were using I couldn't use TT files.

I've fixed the export issue in namespaces, so all generated interfaces inside a namespace are now marked 'export' along with enums.

**Comment by San7hos** [comment]
That is basically my issue as well. Once more, thanks for doing this.
