### ISSUE TITLE
Declare modifier required

### ISSUE THREAD

**Issue by San7hos** [Evertras/typescript-cs-poco#14]
I am getting into one more problem with the TS compiler:

- __Generated\request.d.ts(1,1): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.__
- __Generated\response.d.ts(1,1): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.__

**Comment by San7hos** [comment]
Suggested solution is to change index.js line 165 to **var lines = ['declare module ' + options.baseNamespace + ' {'];**

**Comment by Evertras** [comment]
Fixed in 1.3.6.  Also had to add a 'declare' to enums.  Oops.

**Comment by San7hos** [comment]
You are fast as lightning, thank you very much!

**Comment by San7hos** [comment]
I have no idea how to contact you in a different way. Nevertheless, I would like to personally thank you. Your plugin made my life really easier and I could then easily setup an automatic CI build on my visual studio online.

My thanks to you

**Comment by Evertras** [comment]
Makes me really happy to know it's helped someone out, my pleasure!
