### ISSUE TITLE
C# DateTime to Date instead of string

### ISSUE THREAD

**Issue by ScottRapsey** [Evertras/typescript-cs-poco#17]
Shouldn't a c# DateTime be translated to a typescript Date instead of a string?  
Or at maybe provide an option for this?

**Comment by Evertras** [comment]
In my experience C#'s DateTime doesn't translate directly into a Date.  There's some parsing involved.  That's why I have it set to a string.

If you would find it useful to have the option to define it as a Date, I can add that for sure.

**Comment by ScottRapsey** [comment]
Yeah, I know date/time is hard no matter what you do with it,. There's a whole thing about milliseconds since the 1st of the 1st 1970 UTC, or at the very least the ISO 8601 standard, but I reckon these are problems my serialiser/deserialiser's should deal with. I should be able to deal with it as a date in TS/JS and a DateTime in .Net and not have to give it too much thought (in theory).

I know you've got a production product going here, so a breaking change would be out of the question, but if I could set an option to convert DateTime to date instead of string then that would be awesome. 

(also, thanks for building a very handy little product)

**Comment by Evertras** [comment]
As long as it's clear that this won't magically turn DateTime into Date without custom serialization, I don't think an option hurts anything.  Added in 1.4.0 as dateTImeToDate in the options object.  Set it to true and you'll get Dates instead of strings.
