### ISSUE TITLE
property selector is too restrictive

### ISSUE THREAD

**Issue by mjgoeke** [Evertras/typescript-cs-poco#27]
Currently only public automatic properties with public setter are being exported.

> e.g. public [virtual] int PropName { get; set; }

I would have expected public automatic properties with _private_ setters should be exported.

> e.g. public [virtual] int PropName { get; private set; }

Also is it reasonable to expect public **_fields_** be included?  Public fields seem like the epitome of "POCO".  I was surprised to find they weren't included.

> e.g. public int FieldName;

**Comment by Evertras** [comment]
You are correct on both accounts.  A private set should still be exported in the interface, and fields should also be exported, absolutely.  They just fell through the cracks and haven't come up until now.  Will hopefully have a fix in soonish!

**Comment by Evertras** [comment]
Ok, private setters and bare fields should now both be handled properly in `1.8.1`.  Let me know if you run into anything else!

**Comment by mjgoeke** [comment]
Awesome, thanks!
