### ISSUE TITLE
Allow custom type translations

### ISSUE THREAD

**Issue by xwipeoutx** [Evertras/typescript-cs-poco#32]
DateTimeOffset, for example, should go to a string, but does not.

Allow custom type translations in the options, merge it with the ones in the library.

```
var options = {
  customTypeTranslations: {
    'DateTimeOffset': 'string',
    'System.DateTimeOffset': 'string'
  }
}
```

**Comment by Evertras** [comment]
Added as described in 1.10.0.  Your options object should work as given above.

**Comment by xwipeoutx** [comment]
Wow, thanks for the fast response :)
