### ISSUE TITLE
Interfaces are empty

### ISSUE THREAD

**Issue by rmatejka** [Evertras/typescript-cs-poco#40]
When includeInterfaces option is true, the generated interfaces have no members. The issue is that propertyRegex requires the keyword public but interfaces do not allow that keyword. 

One solution is to pass the type to generateInterface and then use an alternate regex for interfaces:

 var propertyRegex = (options.includeInterfaces && type === "interface"
        ? /( virtual)? ([^?\s]_)(\??) ([\w\d]+)\s_(?:{\s_get;\s_(?:private\s_)?(?:set;)?\s_}|;)/gm
        : /public( virtual)? ([^?\s]_)(\??) ([\w\d]+)\s_(?:{\s_get;\s_(?:private\s_)?set;\s_}|;)/gm
        );

Note virtual is also not permitted but I left in to keep the match indexed correct. I also made the set optional to support read-only properties which were causing parse errors.

Any chance of getting this problem addressed?

Thanks,
Rick

**Comment by ffMathy** [comment]
See if this is still an issue. #42 should have fixed this.
